name: GuildLogger

services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=${PORT}
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=${MONGO_DB}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - SECRET_KEY=${SECRET_KEY}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_AUTH_BASE_URL=${DISCORD_AUTH_BASE_URL}
      - DISCORD_API_BASE_URL=${DISCORD_API_BASE_URL}
      - DISCORD_OAUTH_SCOPES=${DISCORD_OAUTH_SCOPES}
      - DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}
    depends_on:
      - mongo

volumes:
  mongo_data:
